# Generated by Django 4.0.5 on 2022-11-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_product_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
