# Generated by Django 4.0.5 on 2022-11-24 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_product_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='read',
            new_name='seen',
        ),
    ]
