# Generated by Django 4.0.5 on 2022-12-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
