# Generated by Django 4.0.5 on 2022-12-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_api', '0002_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.TextField(),
        ),
    ]
